package com.mycompany.pattern_games.swing;

import com.mycompany.pattern_games.entidades.Jogo;
import com.mycompany.pattern_games.gerenciadores.GerenciadorDeJogo;
import javax.swing.JOptionPane;
import javax.swing.text.Position;

/**
 *
 * @author kaique
 */
public class Edit_Jogo extends javax.swing.JPanel {

    /**
     * Creates new form New_Client
     */
    public Edit_Jogo() {
        initComponents();
        this.jogoJlist.setListData(new GerenciadorDeJogo().listJogo().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pesquisarJogotextFild = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jogoJlist = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        tituloTextFild = new javax.swing.JTextField();
        generoTextFild = new javax.swing.JTextField();
        editarJbutton = new javax.swing.JButton();
        cancelarJbutton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Editar Jogo");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar :");

        pesquisarJogotextFild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisarJogotextFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarJogotextFildActionPerformed(evt);
            }
        });
        pesquisarJogotextFild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisarJogotextFildKeyPressed(evt);
            }
        });

        jogoJlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jogoJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogoJlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jogoJlist);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Genero");

        tituloTextFild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloTextFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTextFildActionPerformed(evt);
            }
        });

        generoTextFild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        editarJbutton.setText("Salvar");
        editarJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJbuttonActionPerformed(evt);
            }
        });

        cancelarJbutton.setText("Calcelar");
        cancelarJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJbuttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarJogotextFild, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                    .addComponent(jSeparator5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(tituloTextFild)
                    .addComponent(generoTextFild, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pesquisarJogotextFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloTextFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generoTextFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarJogotextFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJogotextFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarJogotextFildActionPerformed

    private void tituloTextFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTextFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTextFildActionPerformed

    private void pesquisarJogotextFildKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarJogotextFildKeyPressed
        jogoJlist.setSelectedIndex(jogoJlist.getNextMatch(pesquisarJogotextFild.getText(), 0, Position.Bias.Forward));
    }//GEN-LAST:event_pesquisarJogotextFildKeyPressed

    private void jogoJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogoJlistMouseClicked
        Jogo jogoSelecionado = (Jogo) jogoJlist.getSelectedValue();
        tituloTextFild.setText(jogoSelecionado.getTitulo());
        generoTextFild.setText(jogoSelecionado.getGenero());
    }//GEN-LAST:event_jogoJlistMouseClicked

    private void editarJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJbuttonActionPerformed
        GerenciadorDeJogo gj = new GerenciadorDeJogo();
        Jogo jogoSelecionado = (Jogo) jogoJlist.getSelectedValue();
        jogoSelecionado.setTitulo(tituloTextFild.getText());
        jogoSelecionado.setGenero(generoTextFild.getText());
        if (gj.updateJogo(jogoSelecionado)) {
            JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso.");
        }
    }//GEN-LAST:event_editarJbuttonActionPerformed

    private void cancelarJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJbuttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarJbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarJbutton;
    private javax.swing.JButton editarJbutton;
    private javax.swing.JTextField generoTextFild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JList jogoJlist;
    private javax.swing.JTextField pesquisarJogotextFild;
    private javax.swing.JTextField tituloTextFild;
    // End of variables declaration//GEN-END:variables
}
